### ISSUE TITLE
antenna_phi calculation needs an update

### ISSUE THREAD

**Issue by clark2668** [ara-software/AraSim#36] opened 2020-12-01 19:15 UTC
The calculation of antenna_phi in the GetAngleAnt function is marked as "incorrect" and needs to be updated.

**Comment by MyoungchulK** [comment] 2020-12-03 17:13
Is this issue was existed from the beginning? or become an issue recently.
Because I'm seeing different wf results between the older version and the latest version. 
I ran the same setup file with two versions. 
And setup file is designed to shoot extremely horizontally polarized signals. But it looks like the wf amplitude from the latest version is extremely low.

This is the setting in the setup file
// Nu E spectrum
`EXPONENT=580`

// light bending 0 or 1
`NOFZ=0`

//ver pos
`POSNU_R=507.1638788568871`
`POSNU_THETA=-0.014788621886910634`
`POSNU_PHI=6.269218323341708`

//nu dir
`NNU_THIS_THETA=1`
`NNU_THETA=1.562397559409915`
`NNU_D_THETA=0`

`NNU_THIS_PHI=1`
`NNU_PHI=4.108512700275845`
`NNU_D_PHI=0`

Basically, the vertex is placed at the same depth as the antenna and east side. And Cherenkov cone is designed to go through the antenna(more likely D4BH). It should receive a horizontally polarized E-field. And Hpol will record the highest amplitude.

It looks like the observed amplitude from the latest version is quite low...
the first is the old version and the second is the latest version
![다운로드 (6)](https://user-images.githubusercontent.com/53809378/101063343-08180f00-35d6-11eb-8c75-e1727be4d499.png)
![다운로드 (7)](https://user-images.githubusercontent.com/53809378/101063349-0a7a6900-35d6-11eb-9e71-c003ac33ecb4.png)

If my comment is not caused by this issue, I will look into more:)
Hope this one is helpful for this issue

**Comment by clark2668** [comment] 2020-12-07 00:00
Hey Myoungchul, sorry for the delay here. It is not improbable that they are connected. We are working on a new phi calculation that we hope to push to the master soon. You can revert back to a time before the pol factor calculation was updated, e.g. https://github.com/ara-software/AraSim/commit/ad33fb13ebce3bca38a4e72cf6ed65c61a4bd8a6, if you wanted to check that the event is still sensible there.

**Comment by MyoungchulK** [comment] 2020-12-07 08:48
You are right. the differences are causing by commit #31 ...
I will investigate more and make another issue
And I will clear this message soon from the issue for just phi calculation discussion:)

commit #30 
![commit_30](https://user-images.githubusercontent.com/53809378/101329087-43eff480-38b4-11eb-8f1d-a7e8f553441e.png)
 commit #31 
![commit_31](https://user-images.githubusercontent.com/53809378/101329093-45b9b800-38b4-11eb-9a8e-9a6dda04ce2e.png)

**Comment by MyoungchulK** [comment] 2020-12-07 11:46
I think the above my results are eventually related to this phi calculation issue...
In #31, `pol_factor` is now calculated by `calculatePolFactor` function.
And `thetaHat` and `phiHat` in `calculatePolFactor` are actually using `antenna_phi` which is wrong...
That is actually resulting in the wrong `pol_factor`...  

I pulled out some debug results.
In my setting, I expected `antenna_phi` should be ~**359**deg(placing vertex in the east side of antenna)
And expected `phiHat` would be like **[ 0.01745241  0.9998477   0.        ]** by following the below code.
![Untitled](https://user-images.githubusercontent.com/53809378/101345457-642aae00-38ca-11eb-99e3-bcb667978b2a.png)
But since the actual `antenna_phi` they are using in the simulation is **91.5757**, `phiHat` become a**[ -0.999622,-0.0274971,0 ]**

If we do the inner product `Pol_vector` **[0.0274934,0.999572,-0.0100223]** with each `antenna_phi`
, `pol_factor` will become**0.9998995**(expected) and **0.0549683**(by current phi calculation) which is quite different...

I put some debug lines in the code.
![Untitled1](https://user-images.githubusercontent.com/53809378/101345612-a2c06880-38ca-11eb-83a8-db3688bab3b7.png)

Also, put some previous calculations by the `pokey` and `slappy` for comparing them.
![Untitled2](https://user-images.githubusercontent.com/53809378/101345827-fdf25b00-38ca-11eb-9bf2-7f4a666ea231.png)

And the result looks like this
![Untitled4](https://user-images.githubusercontent.com/53809378/101347607-aef9f500-38cd-11eb-9daf-eea0875dff5f.png)

**(after commit #31)**
ant_type1
antenna_theta:90.088
antenna_phi:**91.5757**
Hpol
phiHat:**-0.999622,-0.0274971,0**
Pol_vector:0.0274934,0.999572,-0.0100223
pol_factor:-0.0549683
pol_factor_abs:**0.0549683**

(before commit #31)
Hpol
n_trg_slappy:**0.0274946,0.999621,-0.00161611**
Pol_vector:0.0274934,0.999572,-0.0100223
pol_factor0:0.999965
pol_factor0_abs:**0.999965**

I think I'm just reminding you of what you already discovered:)
Hope the issue will be fixed soon!
I think that is better than go back to pokey&slappy.

**Comment by clark2668** [comment] 2020-12-07 20:28
@MyoungchulK , if you try with with the fix_phi_calc (https://github.com/ara-software/AraSim/tree/fix_phi_calc) does this event get better? When I tested your event, I found the Hpol pol factor was back up around ~0.98.

**Comment by MyoungchulK** [comment] 2020-12-08 06:38
Yup, as you expected. Thank you for the fix!
![Untitled](https://user-images.githubusercontent.com/53809378/101449059-7872b780-396b-11eb-9188-4f15260ab0c1.png)
The number is slightly different than the above screenshot because of picking up other antenna results from a terminal.
![Untitled1](https://user-images.githubusercontent.com/53809378/101449067-79a3e480-396b-11eb-84ca-785b69ed33de.png)

**Closed as completed** 2021-03-13 22:26 UTC
